### ISSUE TITLE
Wrong `base_size` in data.stat

### ISSUE THREAD

**Issue by shaitan** [reverbrain/eblob#119]
# Problem
`base_size` is a size of blob and its index, but it doesn't include size of unsorted index if blob has both sorted and unsorted index.

# Solution
If sorted index isn't a hardlink to unsorted index, `base_size` should include size of sorted index.

# Question
Why does it keep both sorted and unsorted index for unsorted blob and make sorted index as hardlink to unsorted one after sorting blob?

**Comment by bioothod** [comment]
Looks like this is not relevant anymore since we have one index now, isn't it?

**Comment by shaitan** [comment]
Yep, it is.
